# Site settings
title: IIA4217 - 220888
email: 220888@usn.no
url: https://haavardnk.github.io/IIA4217/
description: "Student project for the course Systems and Control Laboratory, IIA4217 for Håvard Kråkenes"
keywords: "IIA4217, USN"
meta_author: Kråkenes Håvard

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Håvard Kråkenes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
