# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

social:
  - {icon: 'github', link: 'https://github.com/haavardnk/IIA4217'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'


